apiVersion: v1
kind: Service
metadata:
  name: pantry-api
  namespace: pantry-app
  labels:
    app: pantry-api
    app.kubernetes.io/part-of: pantry-platform
spec:
  type: ClusterIP
  selector:
    app: pantry-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
